---
title: "asm2_deep"
author: "Isaac"
date: "3/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## set up
```{r, include=FALSE}
memory.limit(size = 4000000)
# required packages
packages <- c('dplyr','tidyverse', 'tidymodels', 'tidytext', 'discrim','naivebayes', "textrecipes", "kernlab", "splitstackshape", "e1071", "glmnet", "caret", "keras")

# install any packages that are not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# load required packages
invisible(lapply(packages, library, character.only = TRUE))


# load the dataset
t1 <- read_csv("game_train.csv")
glimpse(t1)  
game_test <- read.csv("game_test.csv")
names(t1)

t1$user_suggestion = as.factor(t1$user_suggestion)
```

```{r}
set.seed(1234)
t1_split <- t1 %>%
  filter(nchar(user_review) >= 15) %>%
  initial_split()

t1_train <- training(t1_split)
t1_test <- testing(t1_split)
```



## Create recipe
```{r}
max_words <- 2e4
max_length <- 30

review_rec <- recipe(~ user_review, data = t1) %>%
  step_tokenize(user_review) %>%
  step_tokenfilter(user_review, max_tokens = max_words) %>%
  step_sequence_onehot(user_review, sequence_length = max_length)

review_rec
```

## Prep recipe
```{r}
review_prep <- prep(review_rec)
review_train <- bake(review_prep, new_data = NULL, composition = "matrix")
dim(review_train)


```

## Create LSTM models
```{r}
lstm_mod <- keras_model_sequential() %>%
  layer_embedding(input_dim = max_words + 1, output_dim = 32) %>%
  layer_lstm(units = 32) %>%
  layer_dense(units = 1, activation = "sigmoid")

lstm_mod
```
```{r}
lstm_mod %>%
  compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = c("accuracy")
  )

lstm_history <- lstm_mod %>%
  fit(
    review_train,
    t1_train$user_suggestion,
    epochs = 10,
    validation_split = 0.25,
    batch_size = 512,
    verbose = FALSE
  )

lstm_history

```

```{r}
nb_wf <- workflow() %>%
  add_recipe(suggestion_rec) %>%
  add_model(nb_spec)

nb_wf
```
```{r}
nb_rs <- fit_resamples(
  nb_wf,
  suggestion_folds,
  control = control_resamples(save_pred = TRUE)
)
nb_rs
```


```{r}
nb_rs_metrics <- collect_metrics(nb_rs)
nb_rs_predictions <- collect_predictions(nb_rs)

nb_rs_metrics
```



## Create lasso classification
```{r}
lasso_spec <- logistic_reg(penalty = 0.01, mixture = 1) %>%
  set_mode("classification") %>%
  set_engine("glmnet")

lasso_spec
```
```{r}
lasso_wf <- workflow() %>%
  add_recipe(suggestion_rec) %>%
  add_model(lasso_spec)

lasso_wf
```
```{r}
set.seed(2020)
lasso_rs <- fit_resamples(
  lasso_wf,
  suggestion_folds,
  control = control_resamples(save_pred = TRUE)
)

lasso_rs
```
```{r}
lasso_rs_metrics <- collect_metrics(lasso_rs)
lasso_rs_predictions <- collect_predictions(lasso_rs)

lasso_rs_metrics
```
## Model tuning
```{r}
tune_spec <- logistic_reg(penalty = tune(), mixture = 1) %>%
  set_mode("classification") %>%
  set_engine("glmnet")

tune_spec
```
```{r}
lambda_grid <- grid_regular(penalty(), levels = 30)
lambda_grid
```
```{r}
tune_wf <- workflow() %>%
  add_recipe(suggestion_rec) %>%
  add_model(tune_spec)

set.seed(2020)
tune_rs <- tune_grid(
  tune_wf,
  suggestion_folds,
  grid = lambda_grid,
  control = control_resamples(save_pred = TRUE)
)

tune_rs
```

```{r}
collect_metrics(tune_rs)
tune_rs %>%
  show_best("roc_auc")
```
```{r}
chosen_auc <- tune_rs %>%
  select_by_one_std_err(metric = "roc_auc", -penalty)

chosen_auc
```
```{r}
final_lasso <- finalize_workflow(tune_wf, chosen_auc)

final_lasso
```
```{r}
fitted_lasso <- fit(final_lasso, t1)
```

```{r}
fitted_lasso %>%
  pull_workflow_fit() %>%
  tidy() %>%
  arrange(-estimate)
```

```{r}
fitted_lasso %>%
  pull_workflow_fit() %>%
  tidy() %>%
  arrange(estimate)
```



```{r}
final_model <- fit(final_lasso, t1)

prediction_lasso <- predict(final_model, new_data = t1)
```

##Confusion Matrix
```{r}
y_train <- as.matrix.data.frame(t1$user_suggestion)
y_pred <- as.matrix.data.frame(prediction_lasso)

y_train <- as.factor(y_train)
y_pred <- as.factor(y_pred)

confusionMatrix(y_train, y_pred, mode = "everything", positive="1")
```

##Ouput
```{r}
prediction_lasso_test <- predict(final_model, new_data = game_test)
prediction_lasso_test
```


```{r}
prediction_lasso_test %>% 
  rename(
    user_suggestion = .pred_class
    )

output= data.frame(review_id = game_test$review_id, user_suggestion = prediction_lasso_test)
write.csv(output, "predictions_4.csv", row.names = FALSE, quote = F)
```

